[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm ci --include=dev"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/build/* backend/public/"
]

[start]
cmd = "cd backend && node server.js"