[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build] 
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/build/* backend/public/"
]

[start]
cmd = "cd backend && node server.js"