[variables]
NODE_ENV = "production"

[providers]
node = "18"

[buildCmd]
cmd = "npm run build"

[startCmd] 
cmd = "npm start"

[phases.install]
cmds = ["npm install"]

[phases.build] 
dependsOn = ["install"]
cmds = ["npm run build"]