version: 2
services:
  - type: web
    name: smart-task-planner
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false